oap-project/velox

velox/core/PlanNode.cpp
velox/core/PlanNode.h
velox/exec/ArrowStream.cpp
velox/exec/ArrowStream.h
velox/exec/CMakeLists.txt
velox/exec/LocalPlanner.cpp
velox/vector/arrow/Abi.h

Added a Arrow Stream node to be used as the data source.
An PR was raised to Velox, and the PR id is 1169.

Add arrow stream node

---

velox/substrait/CMakeLists.txt
velox/substrait/SubstraitToVeloxExpr.cpp
velox/substrait/SubstraitToVeloxExpr.h
velox/substrait/SubstraitToVeloxPlan.cpp
velox/substrait/SubstraitToVeloxPlan.h
velox/substrait/SubstraitToVeloxPlanValidator.cpp
velox/substrait/SubstraitToVeloxPlanValidator.h
velox/substrait/SubstraitUtils.cpp
velox/substrait/SubstraitUtils.h
velox/substrait/TypeUtils.cpp
velox/substrait/tests/PlanConversionTest.cpp
velox/substrait/tests/q1_first.json
velox/substrait/tests/q6_first.json

The changes in this PR were raised to Velox and the PR id is 1554.

Support more conversions and added validations

---

velox/substrait/SubstraitToVeloxPlan.cpp
velox/substrait/proto/substrait/algebra.proto

[OPPRO-46] Add dwrf support in substrait

---

.github/workflows/unittest.yml

Signed-off-by: Yuan Zhou <yuan.zhou@intel.com>

compile unit tests on each pull request

---

velox/functions/sparksql/Bitwise.cpp
velox/functions/sparksql/tests/BitwiseTest.cpp

Just add shiftleft and shiftright SparkSQL functions.
Have passed upstream CI, https://github.com/facebookincubator/velox/pull/3358

Add shiftleft and shiftright SparkSQL functions

---

scripts/setup-ubuntu.sh

Similar to:
https://github.com/facebookincubator/velox/commit/d1d323f49a0ca451c3a684c22d63e3269eba7cf3

Use bash to execute the script for installing conda

---

velox/exec/OrderBy.cpp

Issue is exposed from https://github.com/oap-project/gluten/issues/858

Fix unstable sorted result

---

velox/functions/sparksql/Register.cpp
velox/functions/sparksql/String.cpp
velox/functions/sparksql/String.h
velox/functions/sparksql/tests/StringTest.cpp

Have passed upstream CI, https://github.com/facebookincubator/velox/pull/4055

Add sha1 Spark function

---

velox/functions/sparksql/Register.cpp
velox/functions/sparksql/String.h
velox/functions/sparksql/tests/StringTest.cpp

https://github.com/facebookincubator/velox/pull/4092 has been merged

Add sha2 SparkSQL function

---

velox/docs/functions/spark/string.rst
velox/external/utf8proc/utf8procImpl.h
velox/functions/lib/string/StringImpl.h
velox/functions/sparksql/Register.cpp
velox/functions/sparksql/String.h
velox/functions/sparksql/tests/StringTest.cpp

https://github.com/facebookincubator/velox/pull/4199

Add trim/ltrim/rtrim SparkSQL function

---

third_party/CMakeLists.txt

https://github.com/oap-project/gluten/issues/1179

Build is failing on Arrow 11's boost verification

---

velox/substrait/SubstraitToVeloxPlanValidator.cpp

Fix grouping size validation

---

velox/vector/FlatVector-inl.h

After merge https://github.com/oap-project/velox/pull/162 to facebookincubator velox, there are some update(https://github.com/facebookincubator/velox/pull/4413), so we merge it back to oap-project velox.

merge pr4413 from facebookincubator velox

---

velox/expression/CastExpr.cpp

Support casting from bool/date/float to decimal.

Support more cast functions

---

velox/functions/sparksql/aggregates/DecimalAvgAggregate.h

return null when evaluate occur overflow

---

CMake/resolve_dependency_modules/gtest.cmake

Revert "Degrade gtest to 1.10.0"

---

scripts/setup-centos7.sh
scripts/setup-centos8.sh
scripts/setup-helper-functions.sh

Waiting CI test of https://github.com/oap-project/gluten/pull/1198

Update centos7/8 setup script

---

velox/functions/sparksql/aggregates/DecimalAvgAggregate.h

test in https://github.com/oap-project/gluten/pull/1307

optimize decimal avg overflow check

---

velox/functions/sparksql/aggregates/DecimalSumAggregate.h

Bool uses compact representation, use mutableRawValues<uint64_t> and bits::setBit instead.

Extract bool correctly in decimal sum

---

velox/dwio/common/InputStream.cpp
velox/dwio/common/tests/ReadFileInputStreamTests.cpp

implement vread for input stream

implement vread for input stream

---

velox/dwio/parquet/RegisterParquetReader.cpp

* pass velox_dwio_duckdb_parquet_table_scan_test need register duckdb_reader::ParquetReaderFactory.

back out "ParquetReaderType::DUCKDB"

---

velox/functions/sparksql/CMakeLists.txt
velox/functions/sparksql/windows/CMakeLists.txt
velox/functions/sparksql/windows/Register.cpp
velox/functions/sparksql/windows/Register.h
velox/functions/sparksql/windows/RowNumber.cpp
velox/functions/sparksql/windows/RowNumber.h

Remove the changed RowNumber.cpp to sparksql

[GLUTEN--1491]Fix failed velox_windows_rank_test 

---

velox/substrait/SubstraitToVeloxPlan.cpp
velox/substrait/TypeUtils.h

This PR is supposed to fix the fallback issue like below case:
`select * from table where a=true`.

Support bool type for range filter

---

velox/dwio/common/BitConcatenation.cpp

revert Ensure space before updating size

---

.github/workflows/unittest.yml

Enable all tests

---

velox/exec/tests/MultiFragmentTest.cpp

Since customPlanNodeWithExchangeClient is not stable. just remove it temporarily.

Comments unstable ut test

---

velox/dwio/common/SelectiveColumnReaderInternal.h

In function "upcastScalarValues", the current logic is to allocate a buffer to copy the upcasted values to and then copy back to the values buffer. We can do memory copy only once.

removed duplicated memory copy in "upcastScalarValues"

---

velox/dwio/dwrf/common/EncoderUtil.h
velox/dwio/dwrf/common/RLEv2.cpp
velox/dwio/dwrf/common/RLEv2.h
velox/dwio/dwrf/writer/ColumnWriter.cpp
velox/dwio/dwrf/writer/ColumnWriter.h

Added RleEncoderV2 for ORC. Code was modified from https://github.com/apache/orc.

ORC: added RleEncoderV2 support

---

velox/substrait/SubstraitToVeloxPlanValidator.cpp

whitelist approx_distinct agg function

whitelist approx_distinct agg function

---

velox/functions/sparksql/Hash.cpp
velox/substrait/SubstraitToVeloxPlanValidator.cpp

support timestamp hash

---

velox/common/encode/Coding.h
velox/dwio/common/IntDecoder.h
velox/dwio/dwrf/reader/SelectiveLongDecimalColumnReader.cpp

Further improved SelectiveLongDecimalColumnReader. Added decoder for int128_t.

add long decimal type support for ORC

---

velox/functions/lib/string/StringCore.h
velox/functions/lib/string/StringImpl.h
velox/functions/prestosql/StringFunctions.cpp
velox/functions/sparksql/Register.cpp
velox/functions/sparksql/tests/StringTest.cpp

https://github.com/facebookincubator/velox/pull/4922

Fix replace SparkSQL function

---

velox/dwio/dwrf/reader/SelectiveIntegerDirectColumnReader.h
velox/dwio/dwrf/reader/SelectiveLongDecimalColumnReader.h
velox/dwio/dwrf/reader/SelectiveShortDecimalColumnReader.h
velox/dwio/dwrf/reader/SelectiveStringDictionaryColumnReader.cpp
velox/dwio/dwrf/reader/SelectiveStringDictionaryColumnReader.h

we found the crash problems of orc reader in Meituan's test environment

Fix the bug of orc reader test

---

velox/substrait/SubstraitToVeloxPlan.cpp
velox/type/Filter.cpp
velox/type/Filter.h

https://github.com/oap-project/gluten/pull/1832  will test this PR.

Remove unused DoubleValues

---

velox/dwio/dwrf/reader/ColumnReader.cpp
velox/dwio/dwrf/reader/DwrfData.cpp
velox/dwio/dwrf/reader/DwrfData.h
velox/dwio/dwrf/reader/ReaderBase.h
velox/dwio/dwrf/reader/SelectiveByteRleColumnReader.h
velox/dwio/dwrf/reader/SelectiveRepeatedColumnReader.cpp
velox/dwio/dwrf/reader/SelectiveStringDictionaryColumnReader.cpp
velox/dwio/dwrf/reader/SelectiveStringDictionaryColumnReader.h
velox/dwio/dwrf/reader/SelectiveStringDirectColumnReader.cpp
velox/dwio/dwrf/reader/SelectiveStringDirectColumnReader.h
velox/dwio/dwrf/reader/SelectiveStructColumnReader.h
velox/dwio/dwrf/reader/SelectiveTimestampColumnReader.cpp
velox/dwio/dwrf/reader/SelectiveTimestampColumnReader.h
velox/dwio/dwrf/test/ReaderBaseTests.cpp
velox/dwio/dwrf/test/StripeReaderBaseTests.cpp
velox/dwio/dwrf/test/TestStripeStream.cpp

remove some duplicate code to reduce the burden of code maintenance
FYI @zuochunwei @rui-mo @Yuhta

remove some duplicate code used by both DWRF and ORC

---

velox/substrait/SubstraitToVeloxExpr.cpp

Support bigint and decimal for the child field of struct literal.

Support bigint and decimal for the child field of struct literal

---

velox/exec/OrderBy.cpp

Improve performance on Sort operator

s/std::stable_sort/boost::parallel_stable_sort

---

velox/exec/Window.cpp

Related to https://github.com/oap-project/gluten/issues/2025

Add flag for sort in window

---

velox/functions/sparksql/DecimalArithmetic.cpp
velox/type/DecimalUtilOp.h

We should use spark style decimal multiply.

Fix decimal add

---

velox/vector/arrow/Bridge.cpp

This reverts commit bb6a570c13b28c4c0d9028d2878a064fbf6e52e1.

Revert "ld (#317)"

---

velox/functions/sparksql/CMakeLists.txt
velox/functions/sparksql/windows/CMakeLists.txt
velox/functions/sparksql/windows/Register.cpp
velox/functions/sparksql/windows/Register.h
velox/functions/sparksql/windows/RowNumber.cpp
velox/functions/sparksql/windows/RowNumber.h

Revert "refactor spark window function folder"

---

velox/substrait/SubstraitToVeloxPlanValidator.cpp

https://github.com/oap-project/gluten/pull/2196

Add bin function support

---

scripts/setup-helper-functions.sh

https://github.com/oap-project/velox/pull/161 Use sudo to build fb_thrift.

Fix permission problem

---

velox/substrait/SubstraitToVeloxPlanValidator.cpp

Revert "Add bin function support" and add comments

---

velox/row/UnsafeRowFast.cpp

Refer https://github.com/facebookincubator/velox/pull/5311

Fix Unsaferow issue for complex type

---

velox/CMakeLists.txt

Gluten already manage substrait module.

Do not compile substrait module directly

---

velox/exec/CMakeLists.txt
velox/exec/LocalPlanner.cpp
velox/exec/StreamingWindow.cpp
velox/exec/StreamingWindow.h
velox/exec/Window.cpp
velox/exec/Window.h

Streaming window operator differs from the Window operator in that it does not require sorting the input vector or caching all the input data.

Streaming window

---

velox/common/memory/Memory.cpp
velox/common/memory/Memory.h
velox/common/memory/MemoryArbitrator.cpp
velox/common/memory/MemoryArbitrator.h
velox/common/memory/MemoryPool.cpp
velox/common/memory/MemoryPool.h
velox/common/memory/SharedArbitrator.cpp
velox/common/memory/SharedArbitrator.h
velox/common/memory/tests/MemoryManagerTest.cpp
velox/common/memory/tests/MockSharedArbitratorTest.cpp
velox/common/memory/tests/SharedArbitratorTest.cpp
velox/core/QueryCtx.h
velox/dwio/dwrf/test/WriterFlushTest.cpp
velox/exec/GroupingSet.cpp
velox/exec/HashBuild.cpp
velox/exec/HashBuild.h
velox/exec/Operator.cpp
velox/exec/OrderBy.cpp
velox/exec/Task.cpp

Upstream issue https://github.com/facebookincubator/velox/issues/5646, and PRs

Support single thread execution on MemoryPool::reclaim

---

velox/dwio/parquet/writer/Writer.cpp
velox/dwio/parquet/writer/Writer.h

see https://github.com/oap-project/gluten/pull/2435

Support empty dataframe write

---

scripts/setup-helper-functions.sh
velox/common/caching/AsyncDataCache.h
velox/dwio/dwrf/common/RLEv2.h
velox/exec/AggregationHook.h
velox/exec/TaskStructs.h
velox/exec/tests/utils/PlanBuilder.cpp
velox/functions/sparksql/DecimalArithmetic.cpp
velox/type/DecimalUtil.h
velox/type/DecimalUtilOp.h

This pr make oap/velox support compile on macos. It seems the changes are not related to vanilla velox.
see gluten pr https://github.com/oap-project/gluten/pull/2691

Support compile on macos

---

scripts/setup-ubuntu.sh

Remove libunwind.so install in update branch.

Remove libunwind.so install in update branch.

---

velox/connectors/hive/storage_adapters/hdfs/HdfsWriteFile.cpp

Remove the code of creating hdfs path if not existing when writing data in velox.

[GLUTEN-3428] Remove the code of creating hdfs path if not existing in velox
