CMakeLists.txt, velox/connectors/hive/CMakeLists.txt, velox/functions/prestosql/CMakeLists.txt, velox/functions/prestosql/aggregates/CMakeLists.txt
To use Velox in a shared library, its static libraries should be compiled into position independent code.
Several OBJECT settings in Velox was removed, about which an issue was raised to Velox and the issue id is 1047.
=> Add -fPIC and rm OBJECT

velox/substrait/proto/substrait/algebra.proto, velox/substrait/proto/substrait/function.proto, velox/substrait/proto/substrait/parameterized_types.proto, velox/substrait/proto/substrait/plan.proto, velox/substrait/proto/substrait/type_expressions.proto
To satisfy the needs of Meta's internal tests, the Substrait proto files were added with some Velox prefixes, which would cause compilation failure on other test environments. This PR removed them.
=> Remove velox prefix in proto files

velox/substrait/SubstraitToVeloxPlan.cpp, velox/substrait/SubstraitToVeloxPlan.h, velox/substrait/SubstraitToVeloxPlanValidator.cpp, velox/substrait/tests/PlanConversionTest.cpp
Parsed and stored the file format in SubstraitVeloxPlanConverter and then created the corresponding Split according to the specified file format.
=> [OPPRO-46] Support Parquet Read

velox/substrait/SubstraitToVeloxPlan.cpp
Miss some codes in needsRowConstruct.
=> When only groupings exist, set the phase to be Single.

scripts/setup-ubuntu.sh
Or
```
`_ZN6google8protobuf8internal15ThreadSafeArena13thread_cache_E' can not be used when making a shared object
```
Will take place when doing a clean build of Gluten
=> Add -fPIC to PB build

velox/substrait/SubstraitParser.h
This reverts commit bb2d4cbb6e444f2444437063b497bbccc579280d, which is unnecessary after we use a consistent name as substrait's.
=> Revert a commit: Fix the name of bitwise (#93)

velox/dwio/parquet/reader/ParquetReader.cpp
Issue is exposed from https://github.com/oap-project/gluten/issues/770
=> Fix VeloxRuntimeError when reading parquet file with only meta data

velox/exec/HashBuild.cpp
Here,  reserve action doesn't bring benefit.
```
const auto numDependents = outputType->size() - numKeys;
dependentChannels_.reserve(numDependents);
decoders_.reserve(numDependents);
```
Instead, it will cause issues when outputType->size() < numKeys. Such as: https://github.com/oap-project/gluten/issues/790.
So just remove them.
=> Fix hashjoin runtime issue

velox/functions/prestosql/StringFunctions.h
For `right("ab", 3)` expression, vanilla spark will convert the expression to substring("ab", -3). When offload to velox, the start index will be negative. And then the result will be empty, which is not same with vanilla spark "ab". This PR is aim to keep the result same with vanilla spark.
=> Fix the result mismatch for right expression

velox/connectors/hive/HiveConnector.cpp, velox/substrait/SubstraitToVeloxExpr.cpp, velox/substrait/SubstraitToVeloxPlanValidator.cpp, velox/substrait/SubstraitToVeloxPlanValidator.h, velox/vector/BaseVector.h
Make varchar and varbinary compatible. Add validation for cast expression.
=> Make varchar and varbinary compatible

velox/substrait/SubstraitToVeloxPlan.cpp
When the expression is `123 < q1`, Velox will convert it as `q1 < 123` when calculating the filter info. This PR checks if the first argument is a constant, and if so, reverses the function name `(lt => gt, gt => lt, gte => lte, lte => gt)`.
=> Fix wrong batch scan push down filter expression when the expression is 123 < q1

velox/functions/sparksql/RegexFunctions.cpp
We found that RE2 does NOT support lookaround (lookahead/lookbehind) pattern. So the validation should fail on such case for RE2-based implementation, e.g. `rlike`.
See reference link:
https://github.com/google/re2/issues/156
=> Let function validation fail for lookaround pattern in RE2-based implementation

velox/substrait/SubstraitToVeloxPlanValidator.cpp
enable var_samp and var_pop in substrait validator.
=> Enable var_samp and var_pop in validator

velox/dwio/parquet/reader/PageReader.cpp, velox/dwio/parquet/reader/PageReader.h, velox/dwio/parquet/reader/ParquetReader.cpp, velox/dwio/parquet/tests/CMakeLists.txt, velox/dwio/parquet/tests/thrift/CMakeLists.txt, velox/dwio/parquet/tests/thrift/ThriftTransportTest.cpp, velox/dwio/parquet/thrift/ThriftTransport.h
There are two PRs in the velox community to fix such issue: 4160 (merged) &  4108 (pending). We are porting these two patches here with binary file (test purpose) excluded.
=> Port upstream patch to fix parquet reader issue on long min/max string data

velox/substrait/SubstraitToVeloxPlanValidator.cpp
Currently, it is not allowed in Velox to use literal as partition key in window function, which is a rare use case. So we are blocking this case in validator to make fallback possible for this case.
=> Check a fallback case in validation: using literal partition key in window function

velox/exec/HashProbe.cpp
```
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: FINISH
Retriable: False
Expression: isRunning()
Function: checkRunning
File: ../../velox/exec/HashProbe.cpp
Line: 1403
Stack trace:
```
=> INVALID_STATE on HashJoin when spill is turned on

velox/common/strings/ByteStream.h, velox/vector/FlatVector-inl.h
While compile gluten with `BUILD_TESTS=ON` and `GCC12.1.0`, we got two errors.
Error1, the function flush do not implemented.
```
/home/opt/compiler/gcc-12/bin/../lib/gcc/x86_64-pc-linux-gnu/12.1.0/../../../../x86_64-pc-linux-gnu/bin/ld: 
../../releases/libvelox.so: undefined reference to `facebook::strings::ByteSinkBuffer::flush()
```
Error2, seems GCC12 is not smart enough.
```
In file included from /ssd1/zhuxiaoli01/codes/baidu/third-party/gluten/cpp/../ep/build-velox/build/velox_ep/velox/vector/FlatVector.h:514,
from /ssd1/zhuxiaoli01/codes/baidu/third-party/gluten/cpp/../ep/build-velox/build/velox_ep/velox/vector/tests/utils/VectorTestBase.h:21,
from /ssd1/zhuxiaoli01/codes/baidu/third-party/gluten/cpp/velox/tests/ArrowToVeloxTest.cc:22: …
```
=> fix ut compile failed from gluten

CMake/resolve_dependency_modules/gtest.cmake
Latest google test lib has compile error.
```/usr/bin/ld: CMakeFiles/exec_backend_test.dir/BackendTest.cc.o: in function `void testing::internal::RawBytesPrinter::PrintValue<std::type_info, 16ul>(std::type_info const&, std::ostream*)':
/usr/local/include/gtest/gtest-printers.h:270: undefined reference to `testing::internal::PrintBytesInObjectTo(unsigned char const*, unsigned long, std::ostream*)'
/usr/bin/ld: CMakeFiles/exec_backend_test.dir/BackendTest.cc.o: in function `void testing::internal::RawBytesPrinter::PrintValue<gluten::ColumnarBatch, 24ul>(gluten::ColumnarBatch const&, std::ostream*)':
/usr/local/include/gtest/gtest-printers.h:270: undefined reference to `testing::internal::PrintBytesInObjectTo(unsigned char const*, unsigned long, std::ostream*)'```
=> Degrade gtest to 1.10.0

velox/type/DecimalUtil.h
Refer [PR#23](https://github.com/JkSelf/velox/pull/23) to use std::abs instead of abs. Because `abs(int 128)` will cause result mismatch.
=> Change abs to std::abs in decimal operator

velox/functions/sparksql/aggregates/BloomFilterAggAggregate.cpp
Encounter this error when we run q93, we increase settings "spark.sql.optimizer.runtime.bloomFilter.maxNumItems" for our tests. Constants check happens before min comparsion, so when next grouping comes, it failed with not constant value error.
Error Source: USER
Error Code: INVALID_ARGUMENT
Reason: (5404631 vs. 4000000) estimatedNumItems argument must be constant for all input rows
Retriable: False
Expression: newVal == val
Function: setConstantArgument
File: /var/git/Velox/velox/functions/sparksql/aggregates/BloomFilterAggAggregate.cpp
Line: 225
=> Fix bloomfilter validation

scripts/setup-helper-functions.sh
This patch explicitly specified CMAKE_BUILD_TYPE=Release
some folly modules need this flag otherwise it will run with debug mode
https://github.com/facebook/folly/blob/main/folly/Benchmark.cpp#L641
=> Minor: Set cmake build type to Release

velox/exec/Aggregate.cpp, velox/exec/Aggregate.h, velox/exec/AggregateFunctionAdapter.cpp, velox/exec/AggregateFunctionAdapter.h, velox/exec/CMakeLists.txt, velox/exec/HashAggregation.cpp, velox/exec/HashAggregation.h, velox/exec/tests/utils/QueryAssertions.cpp, velox/functions/prestosql/aggregates/AverageAggregate.cpp, velox/functions/prestosql/aggregates/AverageAggregate.h, velox/functions/prestosql/aggregates/BitwiseAggregates.cpp, velox/functions/prestosql/aggregates/CountAggregate.cpp, velox/functions/prestosql/aggregates/CovarianceAggregates.cpp, velox/functions/prestosql/aggregates/MinMaxAggregates.cpp, velox/functions/prestosql/aggregates/SumAggregate.h, velox/functions/prestosql/aggregates/VarianceAggregates.cpp, velox/functions/prestosql/aggregates/tests/AggregateFunctionAdapterTest.cpp, velox/functions/prestosql/aggregates/tests/AverageAggregationTest.cpp, velox/functions/prestosql/aggregates/tests/CMakeLists.txt, velox/functions/sparksql/aggregates/DecimalAvgAggregate.h, velox/functions/sparksql/aggregates/DecimalSumAggregate.h, velox/substrait/SubstraitParser.cpp, velox/substrait/SubstraitParser.h, velox/substrait/SubstraitToVeloxExpr.cpp, velox/substrait/SubstraitToVeloxPlanValidator.cpp, velox/substrait/SubstraitToVeloxPlanValidator.h, velox/type/Variant.cpp, velox/type/Variant.h
To solve `count distinct` issue, use companion function to support mixed aggregation steps.
=> Use companion function to support mixed aggregation steps

velox/core/PlanNode.cpp, velox/core/PlanNode.h, velox/exec/CMakeLists.txt, velox/exec/Expand.cpp, velox/exec/Expand.h, velox/exec/LocalPlanner.cpp, velox/exec/tests/AggregationTest.cpp, velox/exec/tests/PlanNodeToStringTest.cpp, velox/exec/tests/utils/PlanBuilder.cpp, velox/exec/tests/utils/PlanBuilder.h, velox/substrait/SubstraitToVeloxPlan.cpp, velox/substrait/SubstraitToVeloxPlan.h, velox/substrait/SubstraitToVeloxPlanValidator.cpp, velox/substrait/SubstraitToVeloxPlanValidator.h, velox/substrait/proto/substrait/algebra.proto
Add expand op in velox.
This op is different from group id, which accepts projection sets and do the projection. This aligns spark ExpandExec's behavior. We don't need to do the columns' mapping in gluten side.
=> Add expand op in velox

velox/dwio/parquet/writer/Writer.cpp
Change `arrowWriter_->WriteTable()` method to `arrowWriter_->WriteRecordBatch()` in parquet writer.   `arrowWriter_->WriteRecordBatch()` do some optimization to buffer current row group, which can improve the parquet write performance.
=> [GLUTEN-1245] Support parquet write in velox backend

velox/type/tests/TimestampConversionTest.cpp
We support more format in fromDateString function by https://github.com/oap-project/velox/pull/94
So we just change the expectation of failed case. when we met datetime value without day or month we can return true.
For example :
"2000" -> "2000-01-01"
=> Fix velox_type_test

velox/functions/prestosql/DateTimeFunctions.h, velox/functions/prestosql/StringFunctions.h, velox/functions/prestosql/registration/DateTimeFunctionsRegistration.cpp, velox/functions/prestosql/tests/ScalarFunctionRegTest.cpp, velox/functions/sparksql/Register.cpp, velox/functions/sparksql/String.h, velox/functions/sparksql/tests/StringTest.cpp
* presto getYear function return value change to int64_t.
* remove row_constructor_with_null in ScalarFunctionRegTest.cpp. because this function do not have prefix.
* introduce substring function from https://github.com/facebookincubator/velox/pull/4631. And back out presto substring function.
=> Fix velox functions test

velox/core/PlanNode.h, velox/exec/LocalPlanner.cpp, velox/functions/sparksql/Arithmetic.h, velox/functions/sparksql/Register.cpp, velox/functions/sparksql/RegisterArithmetic.cpp, velox/functions/sparksql/tests/DateTimeTest.cpp
- Remove TimestampWithTimeZone support in spark sql.
- Use PModFunction instead of PModIntFunction. PModFunction has bug and fixed in [velox PR 4516](https://github.com/facebookincubator/velox/pull/4516).
=> Pass Velox functions spark test

.github/workflows/unittest.yml, scripts/setup-adapters.sh, scripts/setup-ubuntu.sh, velox/core/PlanNode.h, velox/exec/LocalPlanner.cpp
This patch tries to enable C++ unit tests, in a container. 
The failed tests are excluded temporary, will be added back in another patch.
=> CI: enable unit tests with container

velox/exec/GroupId.cpp, velox/exec/tests/AggregationTest.cpp
1. change expectation for AggregationTest.largeValueRangeArray.  caused by https://github.com/oap-project/velox/pull/98
2. revert gid calculation change caused by https://github.com/oap-project/velox/pull/65
=> Fix velox exec test

velox/substrait/SubstraitToVeloxPlanValidator.cpp
Fallback `arrays_overlap`, `array_min` and `array_max` functions due to incorrect result on NaN.
=> Fallback array functions

velox/functions/sparksql/aggregates/DecimalAvgAggregate.h
Error
```
Stack: [0x00007f7b58327000,0x00007f7b58428000],  sp=0x00007f7b58424750,  free space=1013k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libvelox.so+0xa0a8b9f]  facebook::velox::FlatVector<facebook::velox::UnscaledShortDecimal>::resize(int, bool)+0x2b
C  [libvelox.so+0xa0a0592]  facebook::velox::functions::sparksql::aggregates::DecimalAverageAggregate<facebook::velox::UnscaledLongDecimal, facebook::velox::UnscaledShortDecimal>::extractAccumulators(char**, int, std::shared_ptr<facebook::velox::BaseVector>*)+0xc6
C  [libvelox.so+0xa9146d0]  facebook::velox::exec::Spiller::extractSpill(folly::Range<char**>, std::shared_ptr<facebook::velox::RowVector>&)+0x29c
C  [libvelox.so+0xa914937]  facebook::velox::exec::Spiller::extractSpillVector(std::vecto …
```
=> SIGABRT on DecimalAvgAggregate<UnscaleLongDecimal, UnscaleShortDecimal> when spilling is engaged

velox/core/QueryConfig.h, velox/dwio/common/DataBuffer.h, velox/dwio/parquet/writer/Writer.cpp, velox/dwio/parquet/writer/Writer.h
1. We found that the performance bottleneck is the constant reallocating of the memory pool. The reason is that `DataBuffer ` is directly reallocated in `reverse ` method , and `memcpy ` must be called every time, resulting in performance degradation. Here we adjust the size of each reallocate to 2 times. And the parquet write perf can be 1.31x in 500GB TPC-DS.
2. Revert the changed in [here](https://github.com/oap-project/velox/pull/207) and still use the WriteTable API to write parquet file.
=> Parquet: Optimize parquet write perf

velox/core/PlanNode.h, velox/exec/ArrowStream.cpp, velox/exec/ArrowStream.h
1. Velox cpp file use "velox/vector/arrow/Abi.h"
2. Velox header file use external arrow/Abi.h
=> Avoid include Abi.h twice

velox/dwio/dwrf/common/FileMetadata.cpp, velox/dwio/dwrf/reader/CMakeLists.txt, velox/dwio/dwrf/reader/DwrfReader.cpp, velox/dwio/dwrf/reader/ReaderBase.cpp, velox/dwio/dwrf/reader/SelectiveDwrfReader.cpp, velox/dwio/dwrf/reader/SelectiveLongDecimalColumnReader.cpp, velox/dwio/dwrf/reader/SelectiveLongDecimalColumnReader.h, velox/dwio/dwrf/reader/SelectiveShortDecimalColumnReader.cpp, velox/dwio/dwrf/reader/SelectiveShortDecimalColumnReader.h
I have tested the reading of short decimal type column by query_benchmark
replace #244
=> add decimal column reader support

velox/functions/sparksql/Map.cpp
Fix below failed type check.
```
Validation failed for expression in ProjectRel due to:(ARRAY<INTEGER> vs. ARRAY<INTEGER>) All the key arguments in Map function must be the same!
```
=> Fix type check in MapFunction

velox/functions/sparksql/String.h, velox/functions/sparksql/tests/StringTest.cpp
Since spark's latest releases, like spark 3.2.3/3.3.1 or higher versions, ascii function will return the code point for initial character of given input string. Character with two or more bytes needs to be considered.
=> Align the implementation for ascii function with spark sql 

velox/docs/functions/spark/string.rst, velox/functions/sparksql/String.h, velox/functions/sparksql/tests/StringTest.cpp
https://github.com/facebookincubator/velox/pull/4909
=> Fix chr SparkSQL function

velox/expression/tests/CastExprTest.cpp, velox/functions/lib/tests/DateTimeFormatterTest.cpp, velox/type/Conversions.h, velox/type/TimestampConversion.cpp, velox/type/tests/TimestampConversionTest.cpp
This PR directly changes the code for cast function. In the future, we plan to separate the impl. for common function to respectively adapt to spark/presto semantic.
=> Fix semantic issues in cast function

velox/type/DecimalUtilOp.h
- Fix the wrong result when the length of decimal places is larger than the required scale.
- Support converting a string number of scientific notation to decimal.
- Support rounding a decimal according to the required scale.
With above fixes, cases like below can have correct result.
|  test case  | previous result | correct result in Spark |
| ------------- | ------------- | ------------- |
| cast("0.00000000000000000000000000000000000000000001" as DecimalType(38, 0)) | null  | 0 |
| cast("6E+37" as DecimalType(38, 0))  | null  | 60000000000000000000000000000000000000 |
| cast("9.95" as DecimalType(3, 1))  | 9.9  | 10.0 |
=> Fix casting from string to decimal

velox/expression/CastExpr.cpp, velox/type/Conversions.h
When casting from decimal to bool, Spark only check if a decimal is zero. If yes, the result is true, otherwise false.
=> Fix casting from decimal to bool

velox/dwio/dwrf/common/Common.cpp, velox/dwio/dwrf/common/Common.h, velox/dwio/dwrf/common/FileMetadata.h, velox/dwio/dwrf/reader/ColumnReader.cpp, velox/dwio/dwrf/reader/DwrfData.cpp, velox/dwio/dwrf/reader/DwrfData.h, velox/dwio/dwrf/reader/ReaderBase.cpp, velox/dwio/dwrf/reader/ReaderBase.h, velox/dwio/dwrf/reader/SelectiveByteRleColumnReader.h, velox/dwio/dwrf/reader/SelectiveDwrfReader.cpp, velox/dwio/dwrf/reader/SelectiveFloatingPointColumnReader.h, velox/dwio/dwrf/reader/SelectiveIntegerDictionaryColumnReader.cpp, velox/dwio/dwrf/reader/SelectiveIntegerDirectColumnReader.h, velox/dwio/dwrf/reader/SelectiveLongDecimalColumnReader.h, velox/dwio/dwrf/reader/SelectiveRepeatedColumnReader.cpp, velox/dwio/dwrf/reader/SelectiveShortDecimalColumnReader.h, velox/dwio/dwrf/reader/SelectiveStringDictionaryColumnReader.cpp, velox/dwio/dwrf/reader/SelectiveStringDictionaryColumnReader.h, velox/dwio/dwrf/reader/SelectiveStringDirectColumnReader.cpp, velox/dwio/dwrf/reader/SelectiveStringDirectColumnReader.h, velox/dwio/dwrf/reader/SelectiveStructColumnReader.cpp, velox/dwio/dwrf/reader/SelectiveStructColumnReader.h, velox/dwio/dwrf/reader/SelectiveTimestampColumnReader.cpp, velox/dwio/dwrf/reader/SelectiveTimestampColumnReader.h, velox/dwio/dwrf/reader/StripeReaderBase.cpp, velox/dwio/dwrf/reader/StripeReaderBase.h, velox/dwio/dwrf/reader/StripeStream.cpp, velox/dwio/dwrf/reader/StripeStream.h
Why I do this? please refer to [discussion](https://github.com/facebookincubator/velox/discussions/4933)
We use the `proto::Stream_Kind_xxx` both for `dwrf` and `orc`, and this usage is dangerous, so I refactor this part by the following modifications:
1. add another constructor with a param `proto::orc::Stream` for `DwrfStreamIdentifier`
2. add another member method of `forKind(const proto::orc::Stream_Kind kind)` for `EncodingKey`
3. using union to represent of `proto::orc::StripeFooter* footerOrc_` for orc
4. add `StripeStreams::getEncodingOrc()` for `orc`, the response to  `StripeStreams::getEncoding()` for `dwrf`
5. refactor loadStreams to avoid the mess
6. add `init` for sub-classes of `SelectiveColumnReader`,  check the format in `init()`, call `initDwrf` for dwrf and call …
=> [DWIO] refactor the reader of dwrf/orc

velox/dwio/parquet/reader/ParquetReader.cpp, velox/substrait/SubstraitToVeloxPlanValidator.cpp
The check for int64 is not correct and introduce error when read long with annotation.
add validation check for "regex_extract_all"
=> Ut fix for spark3.3

velox/dwio/common/SelectiveColumnReader.h, velox/dwio/dwrf/reader/SelectiveLongDecimalColumnReader.h, velox/dwio/dwrf/reader/SelectiveShortDecimalColumnReader.h, velox/exec/AggregationHook.h, velox/vector/LazyVector.h
fix the crash caused by `decimal::max/min` In Meituan's orc format environment
=> [ORC] add max/min support for orc decimal reader

velox/exec/Driver.cpp
Velox calculated wrong total time metrics for sort and window operations. `nextOp->noMoreInput()` 's duration is recorded in paraent op's stats, but for sort and window operations, almost all works are executed in `noMoreInput `function. So we observed wrong total time metrics for them.
Before:
After:
=> fix metrics for sort and window operation

scripts/setup-centos7.sh, scripts/setup-centos8.sh
setup-centos.sh will be patched by gluten same as setup-ubuntu.sh.
Require https://github.com/oap-project/gluten/pull/1706
=> Remove install_libhdfs3 from centos setup script

velox/exec/tests/ValuesTest.cpp
Build velox on CentOS 7:
```
$ ./ep/build-velox/src/build_velox.sh --build_benchmarks=ON
...
/opt/gluten/ep/build-velox/build/velox_ep/velox/exec/tests/ValuesTest.cpp: In member function 'virtual void facebook::velox::exec::test::ValuesTest_valuesWithRepeat_Test::TestBody()':
/opt/gluten/ep/build-velox/build/velox_ep/velox/exec/tests/ValuesTest.cpp:86:38: error: call of overloaded 'assertResults(<brace-enclosed initializer list>)' is ambiguous
86 |       .assertResults({input_, input_});
|                                      ^
In file included from /opt/gluten/ep/build-velox/build/velox_ep/velox/exec/tests/ValuesTest.cpp:17:
/opt/gluten/ep/build-velox/build/velox_ep/./velox/exec/tests/utils/AssertQueryBuilder.h:106:25: note: candidate: 'std::shared_ptr<facebook::velox::exec::Task> …
```
=> Fix ambiguous call for devtoolset-9 on CentOS 7

velox/dwio/parquet/writer/Writer.cpp, velox/dwio/parquet/writer/Writer.h
Pick https://github.com/facebookincubator/velox/pull/5322
=> Fix the core dump issue when reading the written parquet file by velox parquet writer

velox/dwio/parquet/writer/Writer.cpp, velox/dwio/parquet/writer/Writer.h
see https://github.com/oap-project/gluten/pull/2039
=> [GLUTEN-2038][VL] Improve parquet write using arrow chunked array

velox/dwio/parquet/reader/ParquetReader.h, velox/dwio/parquet/tests/reader/E2EFilterTest.cpp
The reason why `E2EFilterTest .metadataFilter` failed is that, it tests the filter pushdown using row group metadata but  after https://github.com/oap-project/velox/pull/326 it only has one row group. This prs change the max rows in one row group to 10 which is aligned with the test batch size, so that each batch can produce a row group.
Besides, this pr adds a new test to check we can combine small batches into a big row group.
=> [GLUTEN-2038][VL][FOLLOWUP] Fix and add test

velox/substrait/SubstraitToVeloxPlanValidator.cpp
There are still some compatibility issues for this function. Will re-enable it in a follow-up fix PR.
=> Disable approx_percentile

velox/dwio/common/BufferedInput.h, velox/dwio/parquet/reader/ParquetReader.cpp, velox/dwio/parquet/reader/ParquetReader.h
For small parquet files, when loading footer, the whole file is already read to memory, no need to read file again when loading data.
Before this change:
After this change:
=> Avoid duplicate reading for small parquet files

velox/dwio/common/SelectiveRepeatedColumnReader.cpp, velox/dwio/common/SelectiveRepeatedColumnReader.h, velox/dwio/common/SelectiveStructColumnReader.cpp, velox/dwio/common/SelectiveStructColumnReader.h, velox/dwio/parquet/reader/RepeatedColumnReader.cpp, velox/dwio/parquet/reader/StructColumnReader.cpp
The type of struct reader's output can be different with that from Parquet. This PR fixed the mismatched output type in complex type readers.
=> Fix the output type of complex type vector

velox/dwio/parquet/writer/Writer.cpp, velox/dwio/parquet/writer/Writer.h
Currently the velox parquet writer schema info is wrong. This PR pass the schema from java side to velox parquet writer.
=> Fix parquet write wrong schema  issue

velox/type/Timestamp.h
comments VELOX_DCHECK_* in Timestamp constructor temporarily
=> Comments VELOX_DCHECK_* in Timestamp constructor

third_party/CMakeLists.txt, third_party/arrow_patches/custom-codec.patch, third_party/arrow_patches/memorypool.patch
After degrade the arrow version to 8.0, Gluten no need to re-compile arrow. And we apply the patches into the velox arrow directly.
=> Gluten use the velox arrow 8.0

velox/functions/prestosql/aggregates/MinMaxAggregates.cpp, velox/functions/prestosql/aggregates/tests/MinMaxTest.cpp
support min max aggregation with varbinary type. #385 https://github.com/oap-project/gluten/issues/2169
Gluten CI:https://github.com/oap-project/gluten/pull/2649
=> [VL] [Bug fix] support min max aggregation with varbinary type

velox/dwio/parquet/tests/reader/E2EFilterTest.cpp, velox/functions/prestosql/tests/DecimalArithmeticTest.cpp
Decimal Avg will use https://github.com/facebookincubator/velox/pull/6020.
CombineRowGroup is conflict.
Verified by https://github.com/oap-project/gluten/pull/2572.
=> Comment conflict UT

velox/expression/CastExpr-inl.h
When the length of the string is greater than 12, we store the string in the stringBuffer and save the pointer to the value buffer.
=> Fix the mismatch result issue in TPC-DS Q8

velox/functions/lib/Re2Functions.cpp, velox/functions/lib/Re2Functions.h, velox/functions/sparksql/SplitFunctions.cpp
Failed to compile wip_func_bp branch, due to inconsistent API of vector function factory between this branch and upstream.
=> Fix compile issue for split function

velox/common/base/Exceptions.h
Port a part of code change from https://github.com/facebookincubator/velox/pull/5610 to suppress `VeloxUserError` logs, which can improve performance a lot.
=> Port upstream patch: Do not generate logs for Velox user errors
